"""empty message

Revision ID: 103146aaaad5
Revises: d586336b456e
Create Date: 2022-07-17 20:04:24.554401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103146aaaad5'
down_revision = 'd586336b456e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date_end', sa.Date(), nullable=True))
    op.add_column('event', sa.Column('time_end', sa.Time(), nullable=True))
    op.create_index(op.f('ix_event_date_end'), 'event', ['date_end'], unique=False)
    op.create_index(op.f('ix_event_time_end'), 'event', ['time_end'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_time_end'), table_name='event')
    op.drop_index(op.f('ix_event_date_end'), table_name='event')
    op.drop_column('event', 'time_end')
    op.drop_column('event', 'date_end')
    # ### end Alembic commands ###
