"""introduced group social links

Revision ID: 15f3ed6e152f
Revises: 7ebe4b884dae
Create Date: 2022-09-08 14:24:23.286358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15f3ed6e152f'
down_revision = '7ebe4b884dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'photo',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=True)
    op.add_column('group', sa.Column('instagram', sa.String(length=64), nullable=True))
    op.add_column('group', sa.Column('facebook', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'facebook')
    op.drop_column('group', 'instagram')
    op.alter_column('event', 'photo',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
