"""event photo

Revision ID: 3fda7fa6b442
Revises: 103146aaaad5
Create Date: 2022-07-23 17:14:13.821521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fda7fa6b442'
down_revision = '103146aaaad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('photo', sa.LargeBinary(length=16777216), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'photo')
    # ### end Alembic commands ###
