"""remove event photo

Revision ID: 47f3a9933ead
Revises: 5149f4ec5998
Create Date: 2024-05-18 15:18:04.640250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47f3a9933ead'
down_revision = '5149f4ec5998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', mysql.LONGBLOB(), nullable=True))

    # ### end Alembic commands ###
