"""event table

Revision ID: 588a003602ed
Revises: fd0b3374e97d
Create Date: 2022-03-05 20:28:24.754324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588a003602ed'
down_revision = 'fd0b3374e97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('event', sa.Column('time', sa.Time(), nullable=True))
    op.drop_index('ix_event_start', table_name='event')
    op.create_index(op.f('ix_event_date'), 'event', ['date'], unique=False)
    op.create_index(op.f('ix_event_time'), 'event', ['time'], unique=False)
    op.drop_column('event', 'start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('start', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_event_time'), table_name='event')
    op.drop_index(op.f('ix_event_date'), table_name='event')
    op.create_index('ix_event_start', 'event', ['start'], unique=False)
    op.drop_column('event', 'time')
    op.drop_column('event', 'date')
    # ### end Alembic commands ###
