"""added user tokens

Revision ID: 686b76b51444
Revises: 9ca76467c34a
Create Date: 2022-05-22 14:18:44.840271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686b76b51444'
down_revision = '9ca76467c34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
