"""longer user ids

Revision ID: 7ebe4b884dae
Revises: 3fda7fa6b442
Create Date: 2022-09-05 13:55:56.106098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ebe4b884dae'
down_revision = '3fda7fa6b442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'photo',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=True)
    op.alter_column('user', 'id',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('event', 'photo',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
