"""boolean fields (group.display/permission.granted)

Revision ID: 7f716a599297
Revises: 47f3a9933ead
Create Date: 2024-05-18 20:40:32.006434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f716a599297'
down_revision = '47f3a9933ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display', sa.Boolean(), nullable=False))

    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('granted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.drop_column('granted')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('display')

    # ### end Alembic commands ###
