"""set fields non nullable

Revision ID: 861aa07d567d
Revises: b9f416ab3c3c
Create Date: 2024-05-25 11:04:13.277260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '861aa07d567d'
down_revision = 'b9f416ab3c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=64),
               server_default="",
               nullable=False)
        batch_op.alter_column('tel',
               existing_type=mysql.VARCHAR(length=32),
               server_default="",
               nullable=False)
        batch_op.alter_column('lat',
               existing_type=mysql.DECIMAL(precision=8, scale=6),
               nullable=False)
        batch_op.alter_column('lon',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('date_end',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('time_end',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=2000),
               server_default="",
               nullable=False)

    with op.batch_alter_table('group', schema=None) as batch_op:
           
       batch_op.execute("UPDATE `group` SET group_type = '' WHERE group_type IS NULL")
       batch_op.alter_column('group_type',
              existing_type=mysql.VARCHAR(length=255),
              server_default="",
              nullable=False)
       batch_op.execute("UPDATE `group` SET name = '' WHERE name IS NULL")
       batch_op.alter_column('name',
              existing_type=mysql.VARCHAR(length=64),
              server_default="",
              nullable=False)
       batch_op.execute("UPDATE `group` SET street = '' WHERE street IS NULL")
       batch_op.alter_column('street',
              existing_type=mysql.VARCHAR(length=64),
              server_default="",
              nullable=False)
       batch_op.execute("UPDATE `group` SET zip = '' WHERE zip IS NULL")
       batch_op.alter_column('zip',
              existing_type=mysql.VARCHAR(length=5),
              server_default="",
              nullable=False)
       batch_op.execute("UPDATE `group` SET city = '' WHERE city IS NULL")
       batch_op.alter_column('city',
              existing_type=mysql.VARCHAR(length=64),
              server_default="",
              nullable=False)
       batch_op.execute("UPDATE `group` SET website = '' WHERE website IS NULL")
       batch_op.alter_column('website',
              existing_type=mysql.VARCHAR(length=64),
              server_default="",
              nullable=False)
       batch_op.execute("UPDATE `group` SET instagram = '' WHERE instagram IS NULL")
       batch_op.alter_column('instagram',
              existing_type=mysql.VARCHAR(length=64),
              server_default="",
              nullable=False)
       batch_op.execute("UPDATE `group` SET facebook = '' WHERE facebook IS NULL")
       batch_op.alter_column('facebook',
              existing_type=mysql.VARCHAR(length=64),
              server_default="",
              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('facebook',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('instagram',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('website',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('zip',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('street',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('group_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=True)
        batch_op.alter_column('time_end',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('date_end',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('lon',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               nullable=True)
        batch_op.alter_column('lat',
               existing_type=mysql.DECIMAL(precision=8, scale=6),
               nullable=True)
        batch_op.alter_column('tel',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
