"""empty message

Revision ID: 9ca76467c34a
Revises: cf3b00d56bd6
Create Date: 2022-05-01 23:33:23.569456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca76467c34a'
down_revision = 'cf3b00d56bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manage_land_id', sa.Integer(), nullable=True),
    sa.Column('manage_group_id', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_manager_land', sa.Boolean(), nullable=True),
    sa.Column('is_manager_group', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manage_group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['manage_land_id'], ['land.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
