"""changed group_id to str

Revision ID: b9f416ab3c3c
Revises: 7f716a599297
Create Date: 2024-05-25 10:51:29.543667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9f416ab3c3c'
down_revision = '7f716a599297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_group_id_group', type_='foreignkey')
        batch_op.alter_column('group_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_permission_group_id_group', type_='foreignkey')
        batch_op.alter_column('group_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint('fk_group_parent_id_group', type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_group_parent_id_group', 'group', ['parent_id'], ['id'])

    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_permission_group_id_group', 'group', ['group_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_event_group_id_group', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
