"""lat/lon

Revision ID: cf3b00d56bd6
Revises: 588a003602ed
Create Date: 2022-04-30 16:03:31.199913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3b00d56bd6'
down_revision = '588a003602ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('lat', sa.Numeric(precision=8, scale=6), nullable=True))
    op.add_column('event', sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'lon')
    op.drop_column('event', 'lat')
    # ### end Alembic commands ###
