"""init PfadiTag 2023

Revision ID: f40c045a389a
Revises: 
Create Date: 2023-02-18 15:30:33.364016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40c045a389a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_land'))
    )
    with op.batch_alter_table('land', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_land_name'), ['name'], unique=False)

    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('land_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['land_id'], ['land.id'], name=op.f('fk_region_land_id_land')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region'))
    )
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_region_name'), ['name'], unique=False)

    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('street', sa.String(length=64), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('instagram', sa.String(length=64), nullable=True),
    sa.Column('facebook', sa.String(length=64), nullable=True),
    sa.Column('land_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['land_id'], ['land.id'], name=op.f('fk_group_land_id_land')),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_group_region_id_region')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group'))
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('tel', sa.String(length=32), nullable=True),
    sa.Column('lat', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('photo', sa.LargeBinary(length=16777216), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_event_group_id_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_date_end'), ['date_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_time'), ['time'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_time_end'), ['time_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_title'), ['title'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manage_land_id', sa.Integer(), nullable=True),
    sa.Column('manage_region_id', sa.Integer(), nullable=True),
    sa.Column('manage_group_id', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_manager_land', sa.Boolean(), nullable=True),
    sa.Column('is_manager_region', sa.Boolean(), nullable=True),
    sa.Column('is_manager_group', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manage_group_id'], ['group.id'], name=op.f('fk_user_manage_group_id_group')),
    sa.ForeignKeyConstraint(['manage_land_id'], ['land.id'], name=op.f('fk_user_manage_land_id_land')),
    sa.ForeignKeyConstraint(['manage_region_id'], ['region.id'], name=op.f('fk_user_manage_region_id_region')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('id', name=op.f('uq_user_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_title'))
        batch_op.drop_index(batch_op.f('ix_event_time_end'))
        batch_op.drop_index(batch_op.f('ix_event_time'))
        batch_op.drop_index(batch_op.f('ix_event_date_end'))
        batch_op.drop_index(batch_op.f('ix_event_date'))

    op.drop_table('event')
    op.drop_table('group')
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_name'))

    op.drop_table('region')
    with op.batch_alter_table('land', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_land_name'))

    op.drop_table('land')
    # ### end Alembic commands ###
